# Generated by Django 3.2.8 on 2021-11-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentItemName', models.CharField(max_length=50)),
                ('identityNumber', models.IntegerField()),
                ('rentState', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('rentDate', models.DateTimeField()),
            ],
        ),
    ]
