# Generated by Django 3.2.8 on 2021-11-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_rentitem_identitynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='rentDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='rentState',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='surname',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
