# Generated by Django 3.2.8 on 2021-11-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_rentitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentitem',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rentitem',
            name='rentState',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
